### ISSUE TITLE
GraphQL Gateway Server with Java/Kotlin

### ISSUE THREAD

**Issue by chirdeeptomar** [Netflix/dgs-federation-example#61]
Are there any examples of writing the GraphQL gateway in a JVM based language preferably with Spring Boot. Is this even possible with Netflix DGS? 

Node and Apollo is not a solution for us.

**Comment by SquireOfSoftware** [comment]
Unsure if you are still looking for an answer, I have this problem as well and well after some digging it turns out that Netflix does have a JVM solution to the gateway...but it currently is not out in the wild for us to use.

How do I know this? There is a closed feature request that talks about this here:

https://github.com/Netflix/dgs-framework/issues/697#issuecomment-964661613

So...our options at the moment, appear to be: use Apollo or write our own.

I did do some digging around there are a few topics on this matter:
https://stackoverflow.com/questions/66115567/graphql-federation-is-there-a-java-springboot-gateway

And you don't have that many options.

There is this quote here:
https://www.infoq.com/presentations/netflix-api-graphql-federation/

Where it was quoted: 

> Our gateway is not currently open source, but it is something that we're definitely open to. It's been on our roadmap. If this is something that you'd be interested in using or collaborating on, then do let us know, and they'll help us prioritize the work of supporting that as an open source project.

Anyways hoped that helped, I am thinking of going down the Apollo gateway path to get federated stuff working, as DGS does not really support subgraph stitching (at least from what I have read from their documentation and the examples that they have provided).

**Comment by chirdeeptomar** [comment]
@SquireOfSoftware Thanks for the reply, interesting Netflix has a solution but not Open Source 👎  I have implemented the gateway using Apollo-Gateway  for now.
